@AgentOrchestrator_HostAddress = http://localhost:5081
@TenantName=YOURDOMAIN.onmicrosoft.com
@AgentIdentity=RESULT_FROM_FIRST_REQUEST
@AgentUserName=agentuser1

POST {{AgentOrchestrator_HostAddress}}/api/agentidentity?agentIdentityName=agent%20identity1&agentUserIdentityUpn={{AgentUserName}}@{{TenantName}}
Accept: application/json
Content-Type: application/json

###
POST {{AgentOrchestrator_HostAddress}}/api/customerservice/process
Accept: application/json
Content-Type: application/json

{
 "OrderId": "12345",
 "UserUpn" : "{{AgentUserName}}@{{TenantName}}",
 "AgentIdentity": "{{AgentIdentity}}"
}

###