@AgentOrchestrator_HostAddress = http://localhost:5081

POST {{AgentOrchestrator_HostAddress}}/api/agentidentity?agentIdentityName=agent%20identity1&agentUserIdentityUpn=agentuser1@msidlabtoint.onmicrosoft.com
Accept: application/json
Content-Type: application/json

###
POST {{AgentOrchestrator_HostAddress}}/api/customerservice?agentIdentityName=agent%20identity1&agentUserIdentityUpn=agentuser1@msidlabtoint.onmicrosoft.com

CustomerService


GET {{AgentOrchestrator_HostAddress}}/api/agentidentity
Accept: application/json

###
