@AgentOrchestrator_HostAddress = http://localhost:5081

POST {{AgentOrchestrator_HostAddress}}/api/agentidentity?agentIdentityName=agent%20identity1&agentUserIdentityUpn=agentuser1@msidlabtoint.onmicrosoft.com
Accept: application/json
Content-Type: application/json

###
POST {{AgentOrchestrator_HostAddress}}/api/customerservice/process
Accept: application/json
Content-Type: application/json

{
 "OrderId": "1234",
 "UserUpn" : "agentuser1@msidlabtoint.onmicrosoft.com",
 "AgentIdentity": "c11ec083-2fb9-4d75-99d6-422cd312f589"
}

###

GET {{AgentOrchestrator_HostAddress}}/api/agentidentity
Accept: application/json

###
